/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package louis2.wear.wff

import kotlinx.html.*
import kotlinx.html.stream.createHTML

internal class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}

internal fun <T> TagConsumer<T>.sampleWatchFace(
    width: Int = 480,
    height: Int = 480
): T = watchFace(width = width, height = height) {
    scene(backgroundColor = 0xFF_000003u) {
        bitmapFonts {
            bitmapFont(name = "whatever") {
                for (c in 0..9) character(
                    name = "$c",
                    resource = "whatever/$c.png",
                    width = 20,
                    height = 30
                )
            }
        }
    }
}

internal fun kotlinxHtmlExample() {
    createHTML().html {
        body {
            div outerDiv@{
                lol()
                button {
                    this@outerDiv.lol()
//                    lol()
                }
            }
            h1 { +"Lol" }
            a(href = "https://jetbrains.com")
        }
    }.toString().also { println(it) }
}

internal fun main() {
    println(createHTML(xhtmlCompatible = true).sampleWatchFace())
    kotlinxHtmlExample()
}

//@HtmlTagMarker
internal fun DIV.lol() {

}

